FROM ubuntu:22.04 AS base

# set timezone
RUN apt-get update && \
    apt-get install -yq tzdata && \
    ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

# Install cron
RUN apt-get update && apt-get -y install cron

    
# Set the working directory
WORKDIR /app

# Copy the cron file to the container
COPY remove-uploads-cron /etc/cron.d/cronfile

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/cronfile

# Apply the cron job
RUN crontab /etc/cron.d/cronfile

# Start the cron daemon in the foreground
CMD ["cron", "-f"]