FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive
ARG GIT_ACCESS_TOKEN
ARG OTTER_SERVICE_STDALONE_VERSION

RUN apt-get clean && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y software-properties-common && \
    apt-get update && \
    add-apt-repository -y ppa:longsleep/golang-backports

RUN apt-get install -y python3 && \
    apt-get install -y python3-pip && \
    apt-get install -y curl && \
    apt-get install -y golang
  
RUN echo 'export PATH=$PATH:/root/go/bin' >> /root/.bashrc && \
    go install go.mozilla.org/sops/v3/cmd/sops@v3.7.3

ADD ./requirements.txt /opt/otter-service-stdalone/requirements.txt
RUN python3 -m pip install -r /opt/otter-service-stdalone/requirements.txt

COPY ./dist/otter_service_stdalone-${OTTER_SERVICE_STDALONE_VERSION}.tar.gz /opt/otter-service-stdalone/
RUN python3 -m pip install /opt/otter-service-stdalone/otter_service_stdalone-${OTTER_SERVICE_STDALONE_VERSION}.tar.gz

# install docker cli
ENV DOCKER_VERSION 5:20.10.17~3-0~ubuntu-focal
RUN apt-get update
RUN apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
RUN echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt-get update
RUN apt-get -y install docker-ce-cli=${DOCKER_VERSION}

WORKDIR /opt

EXPOSE 80
ENTRYPOINT ["otter_service_stdalone"]