apiVersion: v1
kind: Service
metadata:
  name: otter-lb
spec:
  selector:
    app: otter-srv-stdalone
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: "34.134.165.169"
