apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.otter_env.name }}-{{ .Values.branch }}
data:
  ENVIRONMENT: {{ .Values.otter_env.parameters.environment }}
  VERBOSE_LOGGING: "{{ .Values.otter_env.parameters.verbose_logging }}"
  GCP_PROJECT_ID: {{ .Values.otter_env.parameters.gcp_project_id }}
  GRADER_DNS: {{ .Values.otter_env.parameters.grader_dns }}
  AUTH_ORG: {{ .Values.otter_env.parameters.auth_org }}
  SUPPORT_EMAIL: {{ .Values.otter_env.parameters.support_email }}
  TARGET_OTTER_VERSION: "{{ .Values.otter_env.parameters.target_otter_version }}"
