{{- if .Values.dind_image.volume_claim.create -}}
{{- $scName := .Values.storageClass.name -}}
{{- $accessMode := .Values.storageClass.accessModes -}}
{{- $storageRequestDocker := .Values.dind_image.storageClassStorageReqest -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.dind_image.volumeClaimName }}
  labels:
    {{- include "otter-service-stdalone.labels" . | nindent 4 }}
spec:
  accessModes: 
    - {{ $accessMode }}
  volumeMode: Filesystem
  storageClassName: {{ $scName }}
  resources:
    requests:
      storage: {{ $storageRequestDocker }}
{{ end }}